#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "RUNNING MY PRESTART HOOK FOR CELERY"
source myenv.sh

export
echo "CELERY IMPORTS ARE: $OPENSHIFT_CELERY_IMPORTS"
